[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.7"
csv = "1.1"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
rust-3d = "0.34.0"